# Generated by Django 6.0.2 on 2026-02-28 13:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('url', 'URL'), ('email', 'Email')], max_length=10)),
                ('target', models.TextField(help_text='The URL or sender email that was scanned')),
                ('result', models.CharField(choices=[('phishing', 'Phishing'), ('legitimate', 'Legitimate'), ('suspicious', 'Suspicious')], max_length=12)),
                ('risk_score', models.FloatField(default=0, help_text='0-100 risk score')),
                ('detection_source', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
