# Generated by Django 6.0.3 on 2026-03-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingUrlDetectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='feedback_label',
            field=models.CharField(blank=True, choices=[('phishing', 'Phishing'), ('legitimate', 'Legitimate')], help_text='What the user says the correct label is', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='user_feedback',
            field=models.CharField(blank=True, choices=[('correct', 'Correct'), ('incorrect', 'Incorrect')], max_length=10, null=True),
        ),
    ]
