# Generated by Django 6.0.3 on 2026-04-01 09:18

import phishingUrlDetectionApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingUrlDetectionApp', '0004_emailverificationtoken_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='token',
            field=models.CharField(default=phishingUrlDetectionApp.models.generate_otp, max_length=6),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default=phishingUrlDetectionApp.models.generate_otp, max_length=6),
        ),
    ]
