# Generated by Django 6.0.3 on 2026-04-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishingUrlDetectionApp', '0005_alter_emailverificationtoken_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainReputationCache',
            fields=[
                ('domain', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_phishing', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.BigIntegerField()),
            ],
            options={
                'db_table': 'domain_reputation_cache',
            },
        ),
        migrations.CreateModel(
            name='ReputationLastUpdate',
            fields=[
                ('source', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reputation_last_update',
            },
        ),
        migrations.CreateModel(
            name='UrlReputationCache',
            fields=[
                ('url', models.TextField(primary_key=True, serialize=False)),
                ('is_phishing', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.BigIntegerField()),
            ],
            options={
                'db_table': 'url_reputation_cache',
            },
        ),
    ]
